-keep class com.pushsignal.PushSignalMessagingService { *; }
-keep class com.pushsignal.PushSignalInitProvider { *; }
-keep class com.pushsignal.PushSignalCenter { *; }
-keep class com.google.firebase.messaging.** { *; }
